---
label: App Config
hide_body: true
fields:
- name: name
  type: text
  config:
    required: false
  label: name
- name: location
  type: text
  config:
    required: false
  label: location
- name: bio
  type: text
  config:
    required: false
  label: bio
- name: avatar
  type: text
  config:
    required: false
  label: avatar
- name: repo
  type: text
  config:
    required: false
  label: repo
- name: contacts
  type: blocks
  label: contacts
  template_types:
  - app-contacts
  config:
    min: 
    max: 
- name: content
  type: blocks
  label: content
  template_types:
  - app-links
  - app-content-preset
  config:
    min: 
    max: 
- name: theme
  type: field_group
  config: {}
  fields:
  - name: contacts
    type: field_group
    config: {}
    fields:
    - name: name
      type: boolean
      label: name
    - name: rounded
      type: boolean
      label: rounded
    - name: full
      type: boolean
      label: full
    label: contacts
  - name: color
    type: text
    config:
      required: false
    label: color
  - name: background
    type: text
    config:
      required: false
    label: background
  - name: repo
    type: boolean
    label: repo
  - name: footer
    type: boolean
    label: footer
  label: theme
