---
label: App Config
hide_body: true
fields:
- name: name
  type: text
  config:
    required: true
  label: name
- name: location
  type: text
  config:
    required: true
  label: location
  default: The Internet
- name: bio
  type: text
  config:
    required: true
  label: bio
- name: avatar
  type: file
  config:
    maxSize: 64
  label: avatar
- name: repo
  type: text
  config:
    required: false
  label: repo
- name: theme
  type: field_group
  config: {}
  fields:
  - name: color
    type: text
    config:
      required: true
    label: color
    default: blue
  - name: background
    type: text
    config:
      required: false
    label: background
  - name: contacts
    type: field_group
    config: {}
    fields:
    - name: name
      type: boolean
      label: name
      default: true
    - name: rounded
      type: boolean
      label: rounded
    - name: full
      type: boolean
      label: full
      default: true
    label: contacts
  - name: repo
    type: boolean
    label: repo
    default: true
  - name: footer
    type: boolean
    label: footer
    default: true
    hidden: false
  label: theme
- name: content
  type: field_group_list
  fields:
  - name: preset
    type: text
    config:
      required: false
    label: preset
  - name: name
    type: text
    config:
      required: false
    label: name
  - name: url
    type: text
    config:
      required: true
    label: url
  - name: invert
    type: boolean
    label: invert
    default: false
  - name: image
    type: file
    config:
      maxSize: 64
    label: image
    default: "/uploads/icon.svg"
  - name: color
    type: text
    config:
      required: false
    label: color
    default: gray
  - name: classes
    type: text
    config:
      required: false
    label: classes
  config:
    min: 
    max: 
    labelField: url
  label: content
- name: contacts
  type: field_group_list
  fields:
  - name: icon
    type: text
    config:
      required: true
    label: icon
    default: account-box
  - name: name
    type: text
    config:
      required: true
    label: name
  - name: uri
    type: text
    config:
      required: true
    label: uri
  config:
    min: 
    max: 
    labelField: name
  label: contacts
pages:
- config/app.json
