---
label: App Config
hide_body: true
fields:
- name: name
  type: text
  config:
    required: false
  label: name
- name: location
  type: text
  config:
    required: false
  label: location
- name: bio
  type: text
  config:
    required: false
  label: bio
- name: avatar
  type: text
  config:
    required: false
  label: avatar
- name: repo
  type: text
  config:
    required: false
  label: repo
- name: contacts
  type: blocks
  label: contacts
  template_types:
  - app-contacts
  config:
    min: 
    max: 
- name: content
  type: blocks
  label: content
  template_types:
  - app-links
  - app-content-preset
  config:
    min: 
    max: 
- name: theme
  type: include
  config: {}
  template: theme
  label: theme
